### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by Wjxfi** [michaelWuensch/BitBanana#18]
or izzyondroid

**Comment by michaelWuensch** [comment]
Thanks for the issue. This is definitely planned.
I'm leaving a link here for myself on how to do this :)
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

**Comment by vivab0rg** [comment]
Or just install using Obtainium in the mean time.

**Comment by michaelWuensch** [comment]
I plan to actually look into F-Droid publishing, once 0.6.3 is out. So probably in july :)

**Comment by michaelWuensch** [comment]
I just made a merge request for inclusion. Waiting for approval.

**Comment by michaelWuensch** [comment]
@Wjxfi BitBanana is now available on F-Droid! :tada: 
https://f-droid.org/en/packages/app.michaelwuensch.bitbanana/
