### ISSUE TITLE
Allow adding lightning addresses as contacts

### ISSUE THREAD

**Issue by jigglycrumb** [michaelWuensch/BitBanana#19]
## Description

Lightning addresses are email like address formats that are easy to use. BitBanana already supports lightning addresses for payments and has a contact list option, but there is no way to add a lightning address as a contact.

## Context

When starting to add a contact, the app instantly starts into a QR scanning mode, without the possibility to enter text.

## Possible Implementation

There could be an in-between screen that lets the user either enter a text (lightning address, pubkey etc) or start the QR scanning mode.

**Comment by michaelWuensch** [comment]
@jigglycrumb 
Thanks for the issue.
I have to think more about how this could be best achieved. I am not sure if contacts should be combinable so one contact can have both a nodeUri and a lnAddress or if you should have to create 2 contacts in that case.
The tricky part is, what do I show as image if a contact has both?

**Comment by jigglycrumb** [comment]
I wouldn't mind having 2 contacts if one person has both. If that makes implementation easier 😄

**Comment by michaelWuensch** [comment]
Yes this is easier and most likely the way I will go.
It will still take a while until this is implemented tough, but it will come :)

**Comment by jigglycrumb** [comment]
Nice, looking forward to it! Thanks for your work!

**Comment by michaelWuensch** [comment]
This feature is implemented now and will be released with the next release.
Please se #33

**Comment by jigglycrumb** [comment]
Very nice, looking forward to testing it! :)

**Comment by michaelWuensch** [comment]
This was released with v0.6.3
