### ISSUE TITLE
[Feature request] Add LUD-18 nameDesc support

### ISSUE THREAD

**Issue by Darth-Coin** [michaelWuensch/BitBanana#21]
## Description
Please add support for adding a pseudonym making a payment to a LNURL, aka [LUD-18](https://github.com/lnurl/luds/blob/luds/18.md)

## Context
This is a very handy feature, when user want to send a message with a sender next to a LNURL payment.
Is not the real identity, it could be any alias or nym. But the receiver could probably know who is sending sats from a donation for example.
And many other applications.

## Possible Implementation
Blixt wallet and OBW already implement it. LNbits and Alby also is using it. So looking into their open source code could be a start.

**Comment by michaelWuensch** [comment]
Thanks for the suggestion!
I'll see what I can do :)

**Comment by michaelWuensch** [comment]
This is implemented now with #29. It will be available in the next release.

**Comment by michaelWuensch** [comment]
This was released with v0.6.3
