### ISSUE TITLE
Show network/chain next to node address

### ISSUE THREAD

**Issue by schildbach** [michaelWuensch/BitBanana#32]
Currently, in the "manage nodes" list and in the title of the main screen there are only addresses listed, not the type of network/chain that is run by the node. So all you can do is guess which is what.

Please consider showing mainnet/testnet/signet next to the address. Alternatively or in addition, a color coding could be used with orange=mainnet, green or gray=testnet and purple=signet.

**Comment by michaelWuensch** [comment]
@schildbach Thanks for the suggestion!
I think it could be easily added to the manage nodes screen. There is enough space.
My current approach would be to not show anything for mainnet, but show the info for other networks. On the spinner on the main page I think it is more difficult though.

Until this feature is added the best solution is to rename your wallets in a way that you can destinguish them without needing to guess.
To do so, go to manage nodes screen, choose one and then tap on rename.

**Comment by michaelWuensch** [comment]
This is done now and shipped with v0.8.0!
