### ISSUE TITLE
🇨🇿 Czech translation is complete 

### ISSUE THREAD

**Issue by bezysoftware** [michaelWuensch/BitBanana#36]
The translation instructions say to celebrate, so here it is 🎉

![obrazek](https://github.com/michaelWuensch/BitBanana/assets/6108688/3dc25073-2444-4154-b752-b3d5e9bbb9bf)

Btw, after rebranding there was a hilarious bug where the original word for "pay", "zaplatit" (notice the "zap" beginning of the word) was translated to "BitBananalatit", which is obviously nonsense :) But at least it made me decide to contribute.

Anyway, keep up the good work!

**Comment by michaelWuensch** [comment]
Awesome! 🎉🥳
Thank you so much.
I did a release yesterday, that already contained most of your translations, but not all. The rest will be included in the next release.

**Comment by michaelWuensch** [comment]
This translation was released with 0.6.5. Thanks again for your contribution!
