### ISSUE TITLE
App crashes when trying to send payment to non-existent lightning address typed via keyboard

### ISSUE THREAD

**Issue by bezysoftware** [michaelWuensch/BitBanana#37]
## Description

When trying to send a payment to non-existent lightning address AND you enter this address manually via keyboard, the app crashes (restarts to be exact). When you scan the same address with a QR code the app correctly shows an error prompt (e.g. 404).

## Expected Behavior

The app should behave the same way when the lightning address is entered via keyboard as it does when scanning the address from a QR code - it should show a red prompt with error description. It shouldn't crash.

## Actual Behavior

The app crashes.

## Steps to Reproduce

Send -> "blabla@blabla123.com" -> Continue -> App crashes

## Context

I was trying to send a payment to someone (donation) but they had disabled their lightning address. The app would crash, restart and prompt for my finger print, which was confusing because at first I though it was asking me to confirm the payment, but I hadn't specified the amount yet.

## Your Environment

- BitBanana version: 0.6.2.44
- Android version: 13
- Device: e.g. Google Pixel 5
- LND Version: 0.16.2

**Comment by michaelWuensch** [comment]
Thanks for the bug report!
I can confirm this still happens in the just released version 0.6.4.
I will fix it asap.

**Comment by michaelWuensch** [comment]
I fixed the bug. Fix will be deployed with next release.

**Comment by michaelWuensch** [comment]
The fix was released with 0.6.5
