### ISSUE TITLE
Differentiate between lightning balance and onchain balance in node.

### ISSUE THREAD

**Issue by BrunswickBTC** [michaelWuensch/BitBanana#61]
The only way to tell the node onchain balance is to attempt to open a channel. It should be easy to check the non-channel balance of the node.  (For example the way zeus does it)

**Comment by michaelWuensch** [comment]
Do you already use version v0.7.0?
It was just released today and it delivered exactly that feature. Use the small yellow arrow under the balance to expand it for more details.
Let me know if that fixed your issue.

**Comment by BrunswickBTC** [comment]
Um, wow! You're so speed at delivering new features is unparalleled. Looks great!

**Comment by michaelWuensch** [comment]
Glad you like it!
I'm closing this issue now. In case you still have issues with this, you can reopen the it.
