### ISSUE TITLE
Test tools can change the amount

### ISSUE THREAD

**Issue by chenhuicui** [michaelWuensch/BitBanana#73]
After setting the amount using the lighting request, click Next. I can modify the specified amount on this Fragment using automated testing frameworks such as Robotium.

## Steps to Reproduce

After setting the amount using the lighting request, click Next. I can modify the specified amount on this Fragment using automated testing frameworks such as Robotium.

**Comment by michaelWuensch** [comment]
Interesting. Do you see this as a security issue?
Right now I don't see what useful attack could be performed with it.

**Comment by chenhuicui** [comment]
Indeed, this issue may not be discovered through manual testing or user use. Haha, I also stumbled upon this issue while conducting some testing tasks. From a tester's perspective, this scenario is unique, and the probability of being attacked is very low. 😄 I think this is a rather interesting spot. :)

**Comment by michaelWuensch** [comment]
I am closing this issue, as I won't change the behavior. If you think this should be addressed, please reopen the issue.
Thanks for mentioning this interesting spot! :)
