### ISSUE TITLE
NonFree dep for F-Droid build

### ISSUE THREAD

**Issue by linsui** [michaelWuensch/BitBanana#77]
org.mariuszgromada.math:MathParser.org-mXparser is not FOSS since v5. See https://github.com/Yet-Zio/yetCalc/issues/98. Could you please exclude it from F-Droid build or downgrade it to v4? Thanks!

**Comment by michaelWuensch** [comment]
@linsui Thanks for reporting this. I now read trough a few comments and I did not know this is incompatible.
Anyway, I just use basic arithmetics of the library, so downgrading shouldn't be a problem. I'll try that.

**Comment by linsui** [comment]
It works, thanks!

**Comment by michaelWuensch** [comment]
@linsui Uhm, what happened? Instead of the new update I made to fix this, a 5 month old version of the app is now shown on F-Droid.
What can I do to fix this? (0.6.7, last version without the dependency, instead of 0.7.5)

**Comment by linsui** [comment]
It's expected. I disabled affected versions and the fixed version hasn't been published. It will be published soon.

**Comment by michaelWuensch** [comment]
Okay, thanks for the info!
