### ISSUE TITLE
Allow paying before fee is estimated

### ISSUE THREAD

**Issue by bezysoftware** [michaelWuensch/BitBanana#78]
Often while paying the fee estimation takes a very long time even though it ends up being 1 or even zero hops. It would be nice to set a maximum allowed fee (percentage?) and enable to pay button even while fee estimation is running. This would greatly improve experience while paying for coffee with a line of ppl behind me.

**Comment by michaelWuensch** [comment]
Thanks for the input.
It is already possible to set a fee limit for lightning transactions in the settings.
From your perspective, what would be the preferred User experience?
A: Don't show a fee estimate at all and just ensure the limit.
B: Calculate the exact fee, but unable to send while it does so (current situation).
C: Calculate fee estimate that can differ from actual fee, but allows sending while calculating.

**Comment by bezysoftware** [comment]
I would prefer option c). It can keep the ui as is, but enable the send button even when fee is being calculated (progress ring is spinning). Bonus would be showing the maximum possible fee calculated from settings and the invoice amount.

**Comment by michaelWuensch** [comment]
Ok, thanks.
I'll see what I can do.
After the change, expect the payment to take about as long as the fee calculation did.
The fee calculation was basically sending a payment that fails on purpose. And then using the route it found to actually do the payment. This way it is possible to calculate the fee exactly, but with the drawback of waiting longer.

**Comment by bezysoftware** [comment]
Thanks. Yes that was my guess, sending a failed payment. But technically the fee is still just a guess because the route might no longer be eligible when I actually pay, right?

**Comment by michaelWuensch** [comment]
This is done now and shipped with v0.8.0!
