### ISSUE TITLE
Scan QR code from image file

### ISSUE THREAD

**Issue by bezysoftware** [michaelWuensch/BitBanana#79]
Someone recently sent me a screenshot an invoice and there was no way for BitBanana to process it without a second device. It would be nice to have a "from file" button on the "Scan" screen, possible next to the flashlight icon.

**Comment by michaelWuensch** [comment]
Ups, sorry, fatfingered the close button on my smartphone... 😅 Reopened!

**Comment by michaelWuensch** [comment]
This is now done. https://github.com/michaelWuensch/BitBanana/commit/192b77e2b6f1e61065b3f9a0e225d48a09c5481e
The feature will be in the next release.

**Comment by michaelWuensch** [comment]
This is fixed now and shipped with v0.8.0!
