### ISSUE TITLE
Brief show of zero balance

### ISSUE THREAD

**Issue by schildbach** [michaelWuensch/BitBanana#80]
## Description

Each startup, BitBanana briefly (and sometimes longer) shows a balance of 0 before the actual balance appears.

## Expected Behavior

I think it should not do that. It's extremely irritating, especially in those cases where that invalid state shows for a longer time.

## Actual Behavior

See description.

## Possible Fix

Show some progress indicator instead: e.g. "Loading balance…"

If the rest of the main screen is usable even without proper balance, the progress could be shown on the main screen with the other buttons already active.

## Steps to Reproduce

1. Start BitBanana.
2. Watch startup closely.

## Your Environment

- BitBanana version: 0.7.4
- Android version: 14
- Device: Pixel 7a
- LND Version: 0.17.4-beta

**Comment by michaelWuensch** [comment]
@schildbach Thanks for the report.
This issue is actually already fixed in the next branch.
There I redid the whole starting procedure during the refactoring for multi backend support and cleaned and improved lots of things.

Should be out with the next update :)

**Comment by michaelWuensch** [comment]
This is fixed now and shipped with v0.8.0!
