### ISSUE TITLE
lndhub connection cannot save - Port input field must not be empty

### ISSUE THREAD

**Issue by monkey-jsun** [michaelWuensch/BitBanana#86]
## Description

When you manually create a lndhub node or modify an existing created from scanning QR code, you will fail to save the config change, because it gives an error message - Port input field must not be empty.  However, there is no port input field in the UI.  In reality, port number is given as part of Host URL.

## Expected Behavior

Should be no error

## Steps to Reproduce

1. Select a LNDhub node
2. Click on "Change data"
3. Click on "Save", and you will get the above error
4.

## Your Environment

- BitBanana version: v0.8.2
- Android version: 14
- Device: Samsung S23
- LND Version: LND 0.17.5-beta on Umbrel host; LNbits + LNDhub extension

**Comment by michaelWuensch** [comment]
Thanks for the notice, I will fix this ASAP

**Comment by michaelWuensch** [comment]
This is fixed now and released with 0.8.3, which is already available on GitHub.
May take a bit until approved in Play Store and available on F-Droid.
