### ISSUE TITLE
Connecting to CLN 24.05 stuck at "Fetching data..."

### ISSUE THREAD

**Issue by sat-hoarder** [michaelWuensch/BitBanana#87]
Added gRPC on CLN 24.05 and am able to connect.  I can see my UTXOs and History but the balance screen is stuck on Fetching data...  Channels are empty as well.  I haven't tried with anything prior to 24.05.

- BitBanana version: 0.8.3 build 60
- Android version: 14
- Device: Samsung Flip5
- CLN Version: 24.05

**Comment by michaelWuensch** [comment]
Thanks for the bug report!
Interesting. I guess one of the API responses during data loading is different than the response my node gave and it fails to parse it. This would cause it to never change the state to "finished".
I will see if I can find the issue but most likely it is hard to replicate for me.
Maybe I have to add the possibility for users to save and view logs.

**Comment by sat-hoarder** [comment]
I would welcome the ability to see logs.  My expectations weren't super high because I'm running the most recent version of CLN and they do change up their API responses often.  I appreciate the work and look forward to an update sometime in future.  Thank you!

**Comment by michaelWuensch** [comment]
It is running fine for me (and for other users) with CLN 24.05 and BitBanana 0.8.3.
So I don't know how to reproduce this.

If you want to help, I invite you to build the app for yourself. Then you can see the Log using Android Studio LogCat and point me in the right direction.
See here on how to build the app:
https://github.com/michaelWuensch/BitBanana/blob/master/docs/INSTALL.md

It would be great if you can help and I'd assist you on the way of course. But I can also understand if that is too much hassle for you.

**Comment by michaelWuensch** [comment]
Closing the issue due to inactivity and no one else mentioning this problem.
