### ISSUE TITLE
lndhub: Failed to authenticate with the Rest API

### ISSUE THREAD

**Issue by TKone7** [michaelWuensch/BitBanana#90]
Cannot connect to my lndhub via http. Getting error "Failed to authenticate with the Rest API".

## Description

I connect to my lndhub running on the same device as lnd. I connect through a private tunnel (Tailscale) but without TLS. The same connection string works in Bluewallet and Zeus but returns an error "Failed to authenticate with the Rest API" on BitBanana. 

In the logs of lndhub I can however see that a request to `GET /balance HTTP/1.1` returned status `200`.  

## Expected Behavior

I would expect the connection to work or that I could configure the connection to ignore TLS checks.

## Actual Behavior

The connection does not work. I assume because of TLS checks.

## Your Environment

- BitBanana version: 0.8.4
- Android version: 13
- LND Version: 0.18.0-beta

**Comment by michaelWuensch** [comment]
@TKone7 
Hm, that is strange, I just tested it and for me it works.
My setup is a raspberry pi with Umbrel. There I insalled LnBits with the LndHub Plugin.
Furthermore I have Tailscale running on the Umbrel.
In the node connection settings in BitBanana I replaced the IP with the tailscale IP and set VPN Automation to Tailscale.

I only could get the error you described if I
- used a wrong IP Address on purpose
- used a wron port on purpose
- used Tailscale IP Address but did not turn on VPN Automation and did not start Tailscale manually either.

But non of that should be your issue when it works with Zeus.

Can you describe your setup in more detail?
And can you provide your connection string (with username, password and IP address replaced with xxx)?

**Comment by TKone7** [comment]
Ah interesting indeed. 
I am running LND on an Intel NUC and running the original LndHub from Bluewallet from [`master`](https://github.com/BlueWallet/LndHub/commit/0cf7387c304d427d5ca2ab8384d0cfa186a97f2f). Apart from that I did pretty much the same as you described.

The fact that I can see the request succeeding in LndHub's logs tells me that the network communication worked fine. Is it possible that the REST API is slightly different LnBits' implementation than LndHub?

I will try out LnBits to see if that works.

**Comment by TKone7** [comment]
Ok, just tried it out and lnbits works flawlessly. Probably not many people running the original LndHub anymore and the project also seems kinda abandoned.

**Comment by michaelWuensch** [comment]
@michaelWuensch Still strange, I tested the original LndHub as well back then. But thanks for the report. I will recheck if LND hub still works.

**Comment by michaelWuensch** [comment]
I found and fixed the issue. Next release will have it included.

**Comment by TKone7** [comment]
Awesome news 💪🏽 Thanks a lot

**Comment by michaelWuensch** [comment]
You are welcome. Check Discord for a test version that also supports LightningTerminal accounts.
