### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [michaelWuensch/BitBanana#92]
## Description

https://gitlab.com/fdroid/fdroiddata/-/jobs/7656844318 The generated license list is a little different. Could you please take a look? Thanks!

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

- BitBanana version: _(e.g. 0.6.0-beta)_
- Android version: _(e.g. API 28)_
- Device: _(e.g. Google Pixel 3)_
- LND Version: _(e.g. 0.7.0-beta)_

**Comment by michaelWuensch** [comment]
Oh no!
Thanks for letting me know. I'll investigate it.

**Comment by michaelWuensch** [comment]
@linsui I just released a new version, that should fix the issue. Lets see if it builds.

**Comment by licaon-kter** [comment]
confirmed, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/61bac924e486653d52b8249bf4c4cb96c14890be

**Comment by linsui** [comment]
Thanks!
