### ISSUE TITLE
UI. Increase fee % precision.

### ISSUE THREAD

**Issue by NilByte** [michaelWuensch/BitBanana#94]
Suggest increasing the fee % precision to better displaying the low fee % that is expected on LN.

![Screenshot_2024-09-15-12-40-03-44_4b5249dbfbf8be09a0747d6d293903ec 1](https://github.com/user-attachments/assets/b4d771ed-4bd1-4a74-a92c-33e731b5095d)

**Comment by michaelWuensch** [comment]
I just added one more decimal, which would have resulted in 0.04% in your example. Fees are not very likely to be much cheaper than this, except when a free route is found. But in that case adding more precision doesn't make sense as well.
I think two fraction digits is a good solution.
Next version will have the change.

**Comment by michaelWuensch** [comment]
This was shipped with 0.8.8
